### PR TITLE
Solves /opt/app.sandstorm/

### PR DESCRIPTION
**Pull request by JamborJan**
Solves https://github.com/zarvox/vagrant-spk/issues/6

### CODE REVIEW

**Comment by paulproteus** [comment]
Thanks for the patch! I'll let @zarvox review it in detail, but it looks basically definitely correct.

I wonder how @rchrd2 was able to use `vagrant-spk` a few days ago!

**Comment by paulproteus** [comment]
Ah hah, now I see -- the bug was introduced recently.

**Comment by JamborJan** [comment]
```vagrant-spk dev``` was working fine but ```vagrant-spk pack``` not in this case.

Anyway, there seem to be some weird things ... still experimenting with https://github.com/JamborJan/paperwork/issues/10 and have no idea where it comes from.

**Comment by zarvox** [comment]
Awesome, thanks a bunch!  Sorry for introducing a regression in one of my recent patchsets, and thanks for fixing it!

**Pull request merged**
